# Generated by Django 3.2.6 on 2022-10-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='clinic',
            name='end',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='start',
            field=models.TimeField(default='08:00'),
        ),
    ]
