# Generated by Django 3.2.6 on 2022-10-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20221010_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Keterangan'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Alamat'),
        ),
    ]
