# Generated by Django 3.2.6 on 2022-10-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapists',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Keterangan'),
        ),
    ]
