# Generated by Django 3.2.6 on 2022-10-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0002_therapists_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapists',
            name='religion',
            field=models.CharField(blank=True, choices=[('CHRISTIAN', 'Kristen'), ('CATHOLIC', 'Katholik'), ('ORTHODOX', 'Orthodox'), ('ISLAM', 'Islam'), ('HINDU', 'Hindu'), ('BUDDHA', 'Budha'), ('KHONGHUCU', 'Khonghucu')], default='CHRISTIAN', max_length=50, null=True, verbose_name='Agama'),
        ),
    ]
