# Generated by Django 3.2.6 on 2022-10-11 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20221011_0618'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nama Paket')),
                ('price', models.IntegerField(verbose_name='Harga Paket')),
                ('session', models.IntegerField(verbose_name='Jumlah Sesi')),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.clinic', verbose_name='Klinik')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Paket',
                'verbose_name_plural': 'Paket',
                'db_table': 'packages',
            },
        ),
    ]
