# Generated by Django 3.2.6 on 2022-10-11 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0006_auto_20221011_1226'),
        ('account', '0003_auto_20221011_0618'),
        ('data_support', '0002_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nama Item')),
                ('price', models.IntegerField(verbose_name='Harga Item')),
                ('discount', models.FloatField(default=0, verbose_name='Diskon (%)')),
                ('final_price', models.IntegerField(default=0, verbose_name='Harga Akhir')),
                ('session', models.IntegerField(default=0, verbose_name='Jumlah Sesi')),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.clinic', verbose_name='Klinik')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Daftar Item',
                'verbose_name_plural': 'Daftar Item',
                'db_table': 'invoice_items',
            },
        ),
        migrations.DeleteModel(
            name='Packages',
        ),
    ]
