# Generated by Django 3.2.6 on 2022-10-11 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_support', '0003_auto_20221011_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitems',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='invoiceitems',
            name='final_price',
        ),
    ]
