# Generated by Django 3.2.6 on 2022-10-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_support', '0004_auto_20221011_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitems',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Keterangan'),
        ),
    ]
