# Generated by Django 3.2.6 on 2022-10-11 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_support', '0005_invoiceitems_additional_info'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invoiceitems',
            table='invoice_items_setting',
        ),
    ]
