# Generated by Django 3.2.6 on 2022-10-10 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_support', '0001_initial'),
        ('account', '0001_initial'),
        ('student', '0002_auto_20221010_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('session', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_support.activities', verbose_name='Activity')),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.clinic', verbose_name='Klinik')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.students', verbose_name='Siswa')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'db_table': 'schedule',
            },
        ),
    ]
