# Generated by Django 3.2.6 on 2022-10-13 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import schedule.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('student', '0001_initial'),
        ('therapist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tanggal')),
                ('start', models.TimeField(verbose_name='Mulai')),
                ('end', models.TimeField(blank=True, null=True, verbose_name='Selesai')),
                ('session', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1, verbose_name='Sesi')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Keterangan')),
                ('is_done', models.BooleanField(default=False, verbose_name='Terapi Selesai')),
                ('activity', models.ForeignKey(limit_choices_to=schedule.models.Schedules.limit_choices_to_current_user, on_delete=django.db.models.deletion.CASCADE, to='data_support.activities', verbose_name='Activity')),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.clinic', verbose_name='Klinik')),
                ('student', models.ForeignKey(limit_choices_to=schedule.models.Schedules.limit_choices_to_current_user, on_delete=django.db.models.deletion.CASCADE, to='student.students', verbose_name='Siswa')),
                ('therapist', models.ForeignKey(limit_choices_to=schedule.models.Schedules.limit_choices_to_current_user, on_delete=django.db.models.deletion.CASCADE, to='therapist.therapists', verbose_name='Therapist')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Jadwal',
                'verbose_name_plural': 'Jadwal',
                'db_table': 'schedule',
            },
        ),
    ]
