# Generated by Django 4.1.2 on 2022-11-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='is_arrived',
            field=models.BooleanField(default=False, verbose_name='Sudah Hadir'),
        ),
    ]
