# Generated by Django 3.2.6 on 2022-10-10 07:52

from django.db import migrations, models
import django.db.models.deletion
import schedule.models


class Migration(migrations.Migration):

    dependencies = [
        ('data_support', '0001_initial'),
        ('therapist', '0001_initial'),
        ('student', '0003_alter_students_clinic'),
        ('schedule', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='activity',
            field=models.ForeignKey(limit_choices_to=schedule.models.Schedules.limit_choices_to_current_user, on_delete=django.db.models.deletion.CASCADE, to='data_support.activities', verbose_name='Activity'),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='student',
            field=models.ForeignKey(limit_choices_to=schedule.models.Schedules.limit_choices_to_current_user, on_delete=django.db.models.deletion.CASCADE, to='student.students', verbose_name='Siswa'),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='therapist',
            field=models.ForeignKey(limit_choices_to=schedule.models.Schedules.limit_choices_to_current_user, on_delete=django.db.models.deletion.CASCADE, to='therapist.therapists', verbose_name='Therapist'),
        ),
    ]
