# Generated by Django 3.2.6 on 2022-10-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20221010_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='start',
            field=models.TimeField(),
        ),
    ]
