# Generated by Django 3.2.6 on 2022-10-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_alter_schedules_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Keterangan'),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='date',
            field=models.DateField(verbose_name='Tanggal'),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='end',
            field=models.TimeField(blank=True, null=True, verbose_name='Selesai'),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='session',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1, verbose_name='Sesi'),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='start',
            field=models.TimeField(verbose_name='Mulai'),
        ),
    ]
