# Generated by Django 3.2.6 on 2022-10-11 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20221011_0617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedules',
            options={'verbose_name': 'Jadwal', 'verbose_name_plural': 'Jadwal'},
        ),
    ]
