# Generated by Django 3.2.6 on 2022-10-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_alter_schedules_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
