# Generated by Django 3.2.6 on 2022-10-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_schedules_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Terapi Selesai'),
        ),
    ]
