# Generated by Django 3.2.6 on 2022-10-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_alter_schedules_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='session',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1, verbose_name='Sesi'),
        ),
    ]
