# Generated by Django 3.2.6 on 2022-10-10 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('student', '0002_auto_20221010_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.clinic', verbose_name='Klinik'),
        ),
    ]
