# Generated by Django 4.1.2 on 2022-11-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_students_options_students_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='pin_lock',
            field=models.BooleanField(default=False, verbose_name='PIN Lock'),
        ),
        migrations.AlterField(
            model_name='students',
            name='pin',
            field=models.CharField(default='8575', max_length=4, verbose_name='PIN'),
        ),
    ]
