# Generated by Django 4.1.2 on 2022-11-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_students_pin_lock_alter_students_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='pin',
            field=models.CharField(default='4053', max_length=4, verbose_name='PIN'),
        ),
    ]
