# Generated by Django 3.2.6 on 2022-10-11 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20221011_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='package_session',
            new_name='session',
        ),
        migrations.RemoveField(
            model_name='students',
            name='package',
        ),
        migrations.DeleteModel(
            name='Packages',
        ),
    ]
