# Generated by Django 3.2.6 on 2022-10-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20221011_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='session_scheduled',
            field=models.IntegerField(default=0, verbose_name='Sesi Terjadwal'),
        ),
        migrations.AddField(
            model_name='students',
            name='session_used',
            field=models.IntegerField(default=0, verbose_name='Sesi Terpakai'),
        ),
        migrations.AlterField(
            model_name='parentfather',
            name='religion',
            field=models.CharField(blank=True, choices=[('CHRISTIAN', 'Kristen'), ('CATHOLIC', 'Katholik'), ('ORTHODOX', 'Orthodox'), ('ISLAM', 'Islam'), ('HINDU', 'Hindu'), ('BUDDHA', 'Budha'), ('KHONGHUCU', 'Khonghucu')], default='CHRISTIAN', max_length=50, null=True, verbose_name='Agama'),
        ),
        migrations.AlterField(
            model_name='parentmother',
            name='religion',
            field=models.CharField(blank=True, choices=[('CHRISTIAN', 'Kristen'), ('CATHOLIC', 'Katholik'), ('ORTHODOX', 'Orthodox'), ('ISLAM', 'Islam'), ('HINDU', 'Hindu'), ('BUDDHA', 'Budha'), ('KHONGHUCU', 'Khonghucu')], default='CHRISTIAN', max_length=50, null=True, verbose_name='Agama'),
        ),
        migrations.AlterField(
            model_name='students',
            name='religion',
            field=models.CharField(blank=True, choices=[('CHRISTIAN', 'Kristen'), ('CATHOLIC', 'Katholik'), ('ORTHODOX', 'Orthodox'), ('ISLAM', 'Islam'), ('HINDU', 'Hindu'), ('BUDDHA', 'Budha'), ('KHONGHUCU', 'Khonghucu')], default='CHRISTIAN', max_length=50, null=True, verbose_name='Agama'),
        ),
        migrations.AlterField(
            model_name='students',
            name='session',
            field=models.IntegerField(default=0, verbose_name='Sesi Tersedia'),
        ),
    ]
