# Generated by Django 3.2.6 on 2022-10-26 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_support', '0001_initial'),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoiceItems',
            new_name='InvoiceForItems',
        ),
    ]
