# Generated by Django 3.2.6 on 2022-10-11 08:47

from django.db import migrations, models
import django.db.models.deletion
import invoice.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20221011_1547'),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='student',
            field=models.ForeignKey(limit_choices_to=invoice.models.Invoices.limit_choices_to_current_user, on_delete=django.db.models.deletion.CASCADE, to='student.students', verbose_name='Siswa'),
        ),
    ]
